Repository Gongju-Unity-Bootcamp/Project-C, pull requests merged in 2024-02, with the labels that each got.

#35 Create 팀 회의
  .github/ISSUE_TEMPLATE/팀 회의
Labels: documentation

#41 에셋-몬스터-사운드
  Project C/Assets/Scenes/LeeHyeukJin/LeeHyeukJin.unity
Labels: enhancement

#42 에셋-보스몬스터-이미지스프라이트
  Project C/Assets/Resource/Sprite/Enemy/Monstro.meta
  Project C/Assets/Resource/Sprite/Enemy/Monstro/Monstro.png
  Project C/Assets/Resource/Sprite/Enemy/Monstro/Monstro.png.meta
  Project C/Assets/Scenes/NamGiSan.meta
  Project C/Assets/Scenes/NamGiSan/NamGiSan.unity
  Project C/Assets/Scenes/NamGiSan/NamGiSan.unity.meta
Labels: enhancement

#44 에셋-보스몬스터-사운드
  Project C/Assets/Resource/Sound/Enemy/Monstro.meta
  Project C/Assets/Resource/Sound/Enemy/Monstro/Sound_Enemy_BossAttackSound.mp3
  Project C/Assets/Resource/Sound/Enemy/Monstro/Sound_Enemy_BossAttackSound.mp3.meta
  Project C/Assets/Resource/Sound/Enemy/Monstro/Sound_Enemy_BossDiveAttackSound.mp3
  Project C/Assets/Resource/Sound/Enemy/Monstro/Sound_Enemy_BossDiveAttackSound.mp3.meta
  Project C/Assets/Resource/Sound/Enemy/Monstro/Sound_Enemy_BossIdleSound.mp3
  Project C/Assets/Resource/Sound/Enemy/Monstro/Sound_Enemy_BossIdleSound.mp3.meta
Labels: enhancement

#45 23-에셋-맵-이미지-스프라이트
  Project C/Assets/Scripts/LeeJinHo/Room.cs
  Project C/Assets/Scripts/LeeJinHo/Room.cs.meta
Labels: documentation

#48 37-에셋-플레이어블-캐릭터-사운드
  Project C/Assets/Resource/Sound/Player/Sound_Player_AttackTears.mp3
  Project C/Assets/Resource/Sound/Player/Sound_Player_AttackTears.mp3.meta
  Project C/Assets/Resource/Sound/Player/Sound_Player_CharacterSelect.mp3
  Project C/Assets/Resource/Sound/Player/Sound_Player_CharacterSelect.mp3.meta
  Project C/Assets/Resource/Sound/Player/Sound_Player_Dead.mp3
  Project C/Assets/Resource/Sound/Player/Sound_Player_Dead.mp3.meta
  Project C/Assets/Resource/Sound/Player/Sound_Player_Hit.mp3
  Project C/Assets/Resource/Sound/Player/Sound_Player_Hit.mp3.meta
Labels: enhancement

#50 적 - 일반몬스터 - Fly 몬스터 구현
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy.meta
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Fly.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Fly.prefab.meta
  Project C/Assets/Scenes/LeeHyeukJin/LeeHyeukJin.unity
  Project C/Assets/Scripts/LeeHyuekJin/AttakFlyController.cs
  Project C/Assets/Scripts/LeeHyuekJin/AttakFlyController.cs.meta
  Project C/Assets/Scripts/LeeHyuekJin/EnemyHealth.cs
  Project C/Assets/Scripts/LeeHyuekJin/FlyController.cs
  Project C/ProjectSettings/TagManager.asset
Labels: enhancement

#53 2-적-일반몬스터-attakfly-몬스터-구현
  Project C/Assets/AstarPathfindingProject/Behaviors/AIDestinationSetter.cs
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/AttakFly.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/AttakFly.prefab.meta
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Bullet.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Bullet.prefab.meta
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Horf.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Horf.prefab.meta
  Project C/Assets/Scripts/LeeHyuekJin/AttakFlyController.cs
Labels: enhancement

#54 에셋 - 아이템 - 사운드
  Project C/Assets/Resource/Sound/Item/Sound_Item_Bomb.wav
  Project C/Assets/Resource/Sound/Item/Sound_Item_Bomb.wav.meta
  Project C/Assets/Resource/Sound/Item/Sound_Item_GetItem.mp3
  Project C/Assets/Resource/Sound/Item/Sound_Item_GetItem.mp3.meta
  Project C/Assets/Resource/Sound/Item/Sound_Item_무적.wav
  Project C/Assets/Resource/Sound/Item/Sound_Item_무적.wav.meta
Labels: documentation, enhancement

#55 8 - 룸 랜덤맵제작
  Project C/Assets/Scripts/LeeJinHo/Map/Door.cs
  Project C/Assets/Scripts/LeeJinHo/Map/Door.cs.meta
Labels: enhancement

#56 적 - 일반몬스터 - Horf 몬스터 구현
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Horf.prefab
  Project C/Assets/Scenes/LeeHyeukJin/LeeHyeukJin.unity
Labels: enhancement

#60 5-플레이어블-캐릭터-이동-구현
  Project C/Assets/Prefabs/ShinJinHyeok/Sprite_Player_Tear.prefab
  Project C/Assets/Prefabs/ShinJinHyeok/Sprite_Player_Tear.prefab.meta
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/ShinJinHyeok/Player_Controller.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Controller.cs.meta
  Project C/ProjectSettings/InputManager.asset
Labels: enhancement

#62 19-플레이어블-캐릭터-공격-구현
  Project C/Assets/Prefabs/ShinJinHyeok/Sprite_Player_Tear.prefab
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/ShinJinHyeok/Player_Attack.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Attack.cs.meta
  Project C/Assets/Scripts/ShinJinHyeok/Player_Bullet.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Bullet.cs.meta
  Project C/Assets/Scripts/ShinJinHyeok/Player_Controller.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_GameManager.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_GameManager.cs.meta
  Project C/Assets/Scripts/ShinJinHyeok/Player_ObjectPooling.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_ObjectPooling.cs.meta
  Project C/ProjectSettings/Physics2DSettings.asset
Labels: enhancement

#65 63-플레이어블-캐릭터-공격-구현-이슈
  Project C/Assets/Scripts/ShinJinHyeok/Player_Attack.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Bullet.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_ObjectPooling.cs
  Project C/ProjectSettings/Physics2DSettings.asset
Labels: enhancement

#67 66-플레이어플-캐릭터-공격-구현-3
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/ShinJinHyeok/Player_Attack.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Bullet.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_ObjectPooling.cs
Labels: enhancement

#68 적 - 일반몬스터 - Gaper 몬스터 구현
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Gaper.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Gaper.prefab.meta
  Project C/Assets/Scenes/LeeHyeukJin/LeeHyeukJin.unity
  Project C/Assets/Scripts/LeeHyuekJin/EnemyHealth.cs
  Project C/Assets/Scripts/LeeHyuekJin/GaperController.cs
  Project C/Assets/Scripts/LeeHyuekJin/GaperController.cs.meta
  Project C/Assets/Scripts/LeeHyuekJin/NaviTest.cs
  Project C/Assets/Scripts/LeeHyuekJin/NaviTest.cs.meta
  Project C/Assets/Scripts/LeeHyuekJin/Test.cs
  Project C/ProjectSettings/TagManager.asset
Labels: enhancement

#74 아이템 - 액티브 - 천사
  Project C/Assets/Scripts/LeeJinHo/Map/MapController.cs
Labels: enhancement

#75 58-룸-navi-시스템-구현
  Project C/Assets/AstarPathfindingProject/Core/AstarPath.cs
  Project C/Assets/Resource/Sprite/Map/basement_TileMap.png.meta
  Project C/Assets/Scenes/LeeHyeukJin/LeeHyeukJin.unity
  Project C/Assets/Scenes/LeeHyeukJin/NaviTest.unity
  Project C/Assets/Scripts/LeeHyuekJin/EnemyCounter.cs
  Project C/Assets/Scripts/LeeHyuekJin/EnemyCounter.cs.meta
  Project C/Assets/Scripts/LeeHyuekJin/EnemyHealth.cs
  Project C/Assets/Scripts/LeeHyuekJin/EnemySpawnController.cs
  Project C/Assets/Scripts/LeeHyuekJin/EnemySpawnController.cs.meta
  Project C/Assets/Scripts/LeeHyuekJin/NaviTest.cs
  Project C/ProjectSettings/TagManager.asset
Labels: enhancement

#78 76 카메라 카메라이동
  Project C/Assets/Scenes/LeeJInho/LeeJInHo.unity
  Project C/Assets/Scripts/LeeJinHo/Map/Room.cs
Labels: enhancement

#77 카메라 - 카메라 이동
  Project C/Assets/Scenes/LeeJInho/LeeJInHo.unity
  Project C/Assets/Scripts/LeeJinHo/Map/Room.cs
Labels: enhancement

#80 59-플레이어블-캐릭터-피격-및-사망-구현
  Project C/Assets/Prefabs/ShinJinHyeok/Sprite_Player_Tear.prefab
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/ShinJinHyeok/Player_Bullet.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Controller.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_GameManager.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Health.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Health.cs.meta
  Project C/Assets/Scripts/ShinJinHyeok/Player_Move.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Move.cs.meta
Labels: enhancement

#92 86-플레이어블-캐릭터-피격-수정-및-추가-구현
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Bullet.prefab
  Project C/Assets/Prefabs/ShinJinHyeok/Player.prefab
  Project C/Assets/Prefabs/ShinJinHyeok/Player.prefab.meta
  Project C/Assets/Prefabs/ShinJinHyeok/Sprite_Player_Tear.prefab
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/ShinJinHyeok/Player_Attack.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Bullet.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_GameManager.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Health.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Move.cs
  Project C/ProjectSettings/Physics2DSettings.asset
Labels: enhancement

#98 적-보스몬스터-강하원거리공격구현
  Project C/Assets/Prefabs/NamGiSan/Monstro.prefab
  Project C/Assets/Scenes/NamGiSan/NamGiSan.unity
  Project C/Assets/Scripts/NamGiSan/Boss_Bullet.cs
  Project C/Assets/Scripts/NamGiSan/Boss_ObjectPooling.cs
  Project C/Assets/Scripts/NamGiSan/MonstroController.cs
Labels: enhancement

#101 룸 - Spawn프리팹
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Bullet.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Obstacle/Materials/Materials.meta
  Project C/Assets/Prefabs/LeeHyuekJin/Obstacle/Materials/Materials/block.mat
  Project C/Assets/Prefabs/LeeHyuekJin/Obstacle/Materials/Materials/block.mat.meta
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnObject/Spawn13.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnObject/Spawn13.prefab.meta
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnObject/Spawn14.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnObject/Spawn14.prefab.meta
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnObject/Spawn15.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnObject/Spawn15.prefab.meta
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnObject/Spawn16.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnObject/Spawn16.prefab.meta
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnObject/Spawn17.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnObject/Spawn17.prefab.meta
  Project C/Assets/Scenes/LeeHyeukJin/NaviTest.unity
  Project C/Assets/Scripts/LeeHyuekJin/MoveNavi.cs
Labels: enhancement

#108 적 - 일반몬스터 - Mulligan
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Mulligan.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Mulligan.prefab.meta
  Project C/Assets/Resource/Sprite/Enemy/Mulligan/Materials.meta
  Project C/Assets/Resource/Sprite/Enemy/Mulligan/Materials/mulliganhead.mat
  Project C/Assets/Resource/Sprite/Enemy/Mulligan/Materials/mulliganhead.mat.meta
  Project C/Assets/Scenes/LeeHyeukJin/NaviTest.unity
  Project C/Assets/Scripts/LeeHyuekJin/Enemy/MulliganController.cs
  Project C/Assets/Scripts/LeeHyuekJin/Enemy/MulliganController.cs.meta
Labels: enhancement

#109 UI - 아이템창 수치 변경 로직
  Project C/Assets/Resource/Item/Angel.prefab
  Project C/Assets/Resource/Item/Attack.prefab
  Project C/Assets/Resource/Item/AttackSpeed.prefab
  Project C/Assets/Resource/Item/Dice.prefab
  Project C/Assets/Resource/Item/Grenade.prefab
  Project C/Assets/Resource/Item/Key.prefab
  Project C/Assets/Resource/Item/Libra.prefab
  Project C/Assets/Resource/Item/Recovery.prefab
  Project C/Assets/Resource/Item/Speed.prefab
  Project C/Assets/Resource/Item/스피드.prefab
  Project C/Assets/Resource/Item/최대체력(보류).prefab
  Project C/Assets/Scenes/LeeJInho/LeeJInHo.unity
  Project C/Assets/Scripts/LeeJinHo/Item/ItemActionController.cs
  Project C/Assets/Scripts/LeeJinHo/Item/Items/Angel.asset
  Project C/Assets/Scripts/LeeJinHo/Item/Items/Attack.asset
  Project C/Assets/Scripts/LeeJinHo/Item/Items/CoolTime.asset
  Project C/Assets/Scripts/LeeJinHo/Item/Items/Dice.asset
  Project C/Assets/Scripts/LeeJinHo/Item/Items/Grenade.asset
  Project C/Assets/Scripts/LeeJinHo/Item/Items/Key.asset
  Project C/Assets/Scripts/LeeJinHo/Item/Items/Libra.asset
  Project C/Assets/Scripts/LeeJinHo/Item/Items/Range.asset
  Project C/Assets/Scripts/LeeJinHo/Item/Items/Recovery.asset
  Project C/Assets/Scripts/LeeJinHo/Item/Items/Speed.asset
  Project C/Assets/Scripts/LeeJinHo/Item/Test_Inventory.cs
  Project C/Assets/Scripts/LeeJinHo/Item/Test_Inventory.cs.meta
  Project C/Assets/Scripts/LeeJinHo/Map/Door.cs
  Project C/Assets/Scripts/LeeJinHo/Map/Room.cs
  Project C/Assets/Scripts/LeeJinHo/Test.meta
  Project C/Assets/Scripts/LeeJinHo/Test/Test_Player_Move.cs
  Project C/Assets/Scripts/LeeJinHo/Test/Test_Player_Move.cs.meta
  Project C/ProjectSettings/TagManager.asset
Labels: enhancement

#110 적-보스몬스터-총알프리팹
  Project C/Assets/Prefabs/NamGiSan/Boss_bullet.prefab
  Project C/Assets/Prefabs/NamGiSan/Player_toBoss.prefab
  Project C/Assets/Prefabs/NamGiSan/Player_toBoss.prefab.meta
  Project C/Assets/Resource/Sprite/Enemy/Monstro/Sprite_Boss_Tears.png
  Project C/Assets/Resource/Sprite/Enemy/Monstro/Sprite_Boss_Tears.png.meta
  Project C/Assets/Scenes/NamGiSan/NamGiSan.unity
  Project C/Assets/Scripts/NamGiSan/BossHealth.cs
  Project C/Assets/Scripts/NamGiSan/Boss_Bullet.cs
  Project C/Assets/Scripts/NamGiSan/Boss_ObjectPooling.cs
  Project C/Assets/Scripts/NamGiSan/MonstroController.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Move.cs
Labels: enhancement

#116 버그해결-보스몬스터-투사체피격
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Bullet.prefab
  Project C/Assets/Prefabs/NamGiSan/Boss_bullet.prefab
  Project C/Assets/Prefabs/NamGiSan/Monstro.prefab
  Project C/Assets/Scenes/NamGiSan/NamGiSan.unity
  Project C/Assets/Scripts/NamGiSan/BossHealth.cs
  Project C/Assets/Scripts/NamGiSan/Boss_ObjectPooling.cs
  Project C/Assets/Scripts/NamGiSan/MonstroController.cs
  Project C/ProjectSettings/TagManager.asset
Labels: bug

#118 버그-재업로드
  Project C/Assets/Scripts/NamGiSan/Boss_Bullet.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Bullet.cs
Labels: bug

#121 보스룸 생성
  Project C/Assets/Prefabs/NamGiSan/Monstro.prefab
  Project C/Assets/Scenes/LeeHyeukJin/NaviTest.unity
  Project C/Assets/Scripts/LeeHyuekJin/SpawnBoss.cs
  Project C/Assets/Scripts/LeeHyuekJin/SpawnBoss.cs.meta
  Project C/Assets/Scripts/NamGiSan/MonstroController.cs
Labels: enhancement

#122 UI-메인씬 추가
  Project C/Assets/Scripts/LeeJinHo/Map/New Folder.meta
Labels: enhancement

#131 보스룸, 키룸 생성
  Project C/Assets/Resource/Sprite/Item/Items.png.meta
  Project C/Assets/Scenes/LeeJInho/LeeJInHo.unity
  Project C/Assets/Scenes/LeeJInho/LeeJInHo.unity.meta
  Project C/Assets/Scenes/LeeJInho/Test.unity
  Project C/Assets/Scenes/LeeJInho/Test.unity.meta
Labels: enhancement

#133 아이템 - 보물상자
  Project C/Assets/Animation/ItemBox.meta
  Project C/Assets/Animation/ItemBox/Box.playable
  Project C/Assets/Animation/ItemBox/Box.playable.meta
  Project C/Assets/Animation/ItemBox/BoxClose.anim
  Project C/Assets/Animation/ItemBox/BoxClose.anim.meta
  Project C/Assets/Animation/ItemBox/BoxClose.controller
  Project C/Assets/Animation/ItemBox/BoxClose.controller.meta
  Project C/Assets/Animation/ItemBox/BoxOpen.anim
  Project C/Assets/Animation/ItemBox/BoxOpen.anim.meta
  Project C/Assets/Animation/ItemBox/BoxOpen.controller
  Project C/Assets/Animation/ItemBox/BoxOpen.controller.meta
  Project C/Assets/Box Signal.signal
  Project C/Assets/Box Signal.signal.meta
  Project C/Assets/Prefabs/LeeJinHo/NormalBox.prefab
  Project C/Assets/Prefabs/LeeJinHo/NormalBox.prefab.meta
  Project C/Assets/Resource/Box.meta
  Project C/Assets/Scenes/LeeJInho/LeeJInHo.unity
  Project C/Assets/Scripts/LeeJinHo/Item/Box.cs
  Project C/Assets/Scripts/LeeJinHo/Item/Box.cs.meta
  Project C/Assets/Scripts/LeeJinHo/Item/BoxOpen.playable
  Project C/Assets/Scripts/LeeJinHo/Item/BoxOpen.playable.meta
  Project C/Assets/Scripts/LeeJinHo/New Folder.meta
Labels: enhancement

#136 129-플레이어블-캐릭터-아이템-사용
  Project C/Assets/Prefabs/ShinJinHyeok/Sprite_Player_Tear.prefab
  Project C/Assets/Resource/Sprite/Player/Tears.png
  Project C/Assets/Resource/Sprite/Player/Tears.png.meta
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/LeeJinHo/Item/Item.cs
  Project C/Assets/Scripts/LeeJinHo/Item/ItemActionController.cs
  Project C/Assets/Scripts/LeeJinHo/Item/Test_Inventory.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Attack.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Bullet.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_GameManager.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Move.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_ObjectPooling.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Stat.cs
Labels: enhancement

#138 UI-일시정지UI구현
  Project C/Assets/Resource/Sprite/Menu/HpFill.png
  Project C/Assets/Resource/Sprite/Menu/HpFill.png.meta
  Project C/Assets/Resource/Sprite/Menu/Stage_BG.png
  Project C/Assets/Resource/Sprite/Menu/Stage_BG.png.meta
  Project C/Assets/Resource/Sprite/Menu/emptybar.png
  Project C/Assets/Resource/Sprite/Menu/emptybar.png.meta
  Project C/Assets/Resource/Sprite/Menu/pauseScrene.png
  Project C/Assets/Resource/Sprite/Menu/pauseScrene.png.meta
  Project C/Assets/Resource/Sprite/Menu/pausescreen 1.png
  Project C/Assets/Resource/Sprite/Menu/skull.png
  Project C/Assets/Resource/Sprite/Menu/skull.png.meta
  Project C/Assets/Scenes/NamGiSan/Pause.unity
  Project C/Assets/Scripts/NamGiSan/PauseMenu.cs
  Project C/Assets/Scripts/NamGiSan/PauseMenu.cs.meta
Labels: enhancement

#148 적-보스몬스터-애니메이션구현
  Project C/Assets/Animation/Enemy/Monstro.meta
  Project C/Assets/Animation/Enemy/Monstro/Animator_Enemy_Monstro.controller
  Project C/Assets/Animation/Enemy/Monstro/Animator_Enemy_Monstro.controller.meta
  Project C/Assets/Animation/Enemy/Monstro/Chase.anim
  Project C/Assets/Animation/Enemy/Monstro/Chase.anim.meta
  Project C/Assets/Animation/Enemy/Monstro/ChaseEnd.anim
  Project C/Assets/Animation/Enemy/Monstro/ChaseEnd.anim.meta
  Project C/Assets/Animation/Enemy/Monstro/Crash.anim
  Project C/Assets/Animation/Enemy/Monstro/Crash.anim.meta
  Project C/Assets/Animation/Enemy/Monstro/Dive.anim
  Project C/Assets/Animation/Enemy/Monstro/Dive.anim.meta
  Project C/Assets/Animation/Enemy/Monstro/HighJump.anim
  Project C/Assets/Animation/Enemy/Monstro/HighJump.anim.meta
  Project C/Assets/Animation/Enemy/Monstro/Idle.anim
  Project C/Assets/Animation/Enemy/Monstro/Idle.anim.meta
  Project C/Assets/Animation/Enemy/Monstro/JumpReady.anim
  Project C/Assets/Animation/Enemy/Monstro/JumpReady.anim.meta
  Project C/Assets/Animation/Enemy/Monstro/SpitAttack.anim
  Project C/Assets/Animation/Enemy/Monstro/SpitAttack.anim.meta
  Project C/Assets/Animation/Enemy/Monstro/SpitReady.anim
  Project C/Assets/Animation/Enemy/Monstro/SpitReady.anim.meta
  Project C/Assets/Prefabs/NamGiSan/Boss_bullet.prefab
  Project C/Assets/Prefabs/NamGiSan/Monstro.prefab
  Project C/Assets/Resource/Sprite/Enemy/Monstro/Monstro 1.png
  Project C/Assets/Resource/Sprite/Enemy/Monstro/Monstro 1.png.meta
  Project C/Assets/Scenes/NamGiSan/NamGiSan.unity
  Project C/Assets/Scripts/NamGiSan/MonstroController.cs
Labels: enhancement

#151 146-아이템-상자-아이템-드랍
  Project C/Assets/Resource/Sprite/Player/Sprite_Player_Tears_1.png
  Project C/Assets/Resource/Sprite/Player/Sprite_Player_Tears_1.png.meta
  Project C/Assets/Resource/Sprite/Player/Sprite_Player_Tears_2.png
  Project C/Assets/Resource/Sprite/Player/Sprite_Player_Tears_2.png.meta
  Project C/Assets/Resource/Sprite/Player/Tears.png.meta
  Project C/Assets/Resource/Sprite/Player/tear_pop.png
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/LeeJinHo/Item/Box.cs
  Project C/Assets/Scripts/LeeJinHo/Item/Item.cs
  Project C/Assets/Scripts/LeeJinHo/Item/ItemActionController.cs
  Project C/Assets/Scripts/LeeJinHo/Item/Test_Inventory.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Attack.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Move.cs
Labels: enhancement

#162 159-아이작-시스템-FSM-구현
  Project C/Assets/Animation/Issac.meta
  Project C/Assets/Animation/Issac/Body.controller
  Project C/Assets/Animation/Issac/Body.controller.meta
  Project C/Assets/Animation/Issac/DownAttack.anim
  Project C/Assets/Animation/Issac/DownAttack.anim.meta
  Project C/Assets/Animation/Issac/DownMove.anim
  Project C/Assets/Animation/Issac/DownMove.anim.meta
  Project C/Assets/Animation/Issac/Head.controller
  Project C/Assets/Animation/Issac/Head.controller.meta
  Project C/Assets/Animation/Issac/IdleAttack.anim
  Project C/Assets/Animation/Issac/IdleAttack.anim.meta
  Project C/Assets/Animation/Issac/IdleMove.anim
  Project C/Assets/Animation/Issac/IdleMove.anim.meta
  Project C/Assets/Animation/Issac/LeftAttack.anim
  Project C/Assets/Animation/Issac/LeftAttack.anim.meta
  Project C/Assets/Animation/Issac/LeftMove.anim
  Project C/Assets/Animation/Issac/LeftMove.anim.meta
  Project C/Assets/Animation/Issac/RightAttack.anim
  Project C/Assets/Animation/Issac/RightAttack.anim.meta
  Project C/Assets/Animation/Issac/RightMove.anim
  Project C/Assets/Animation/Issac/RightMove.anim.meta
  Project C/Assets/Animation/Issac/Tears_Bullet_1.anim
  Project C/Assets/Animation/Issac/Tears_Bullet_1.anim.meta
  Project C/Assets/Animation/Issac/Tears_Bullet_2.anim
  Project C/Assets/Animation/Issac/Tears_Bullet_2.anim.meta
  Project C/Assets/Animation/Issac/Tears_ver_1.controller
  Project C/Assets/Animation/Issac/Tears_ver_1.controller.meta
  Project C/Assets/Animation/Issac/UpAttack.anim
  Project C/Assets/Animation/Issac/UpAttack.anim.meta
  Project C/Assets/Animation/Issac/UpMove.anim
  Project C/Assets/Animation/Issac/UpMove.anim.meta
  Project C/Assets/Plugins/CsvHelper.dll
  Project C/Assets/Plugins/CsvHelper.dll.meta
  Project C/Assets/Resource/Sprite/Player/Sprite_Player_Isaac.png.meta
  Project C/Assets/Resource/Sprite/Player/Sprite_Player_Tears_1.png.meta
  Project C/Assets/Resource/Sprite/Player/Sprite_Player_Tears_2.png.meta
  Project C/Assets/Resources.meta
  Project C/Assets/Resources/Prefab.meta
  Project C/Assets/Resources/Prefab/Issac.meta
  Project C/Assets/Resources/Prefab/Issac/Issac.prefab
  Project C/Assets/Resources/Prefab/Issac/Issac.prefab.meta
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/Issac.meta
  Project C/Assets/Scripts/Issac/IssacController.cs
  Project C/Assets/Scripts/Issac/IssacController.cs.meta
  Project C/Assets/Scripts/ShinJinHyeok/IsaacController.cs
  Project C/Assets/Scripts/ShinJinHyeok/IsaacController.cs.meta
  Project C/ProjectSettings/ProjectSettings.asset
Labels: enhancement

#165 적-보스몬스터-애니메이션보완
  Project C/Assets/Animation/Enemy/Monstro/Animator_Enemy_Monstro.controller
  Project C/Assets/Animation/Enemy/Monstro/Chase.anim
  Project C/Assets/Animation/Enemy/Monstro/ChaseEnd.anim
  Project C/Assets/Animation/Enemy/Monstro/ChaseEnd.anim.meta
  Project C/Assets/Animation/Enemy/Monstro/Crash.anim
  Project C/Assets/Animation/Enemy/Monstro/Dive.anim
  Project C/Assets/Animation/Enemy/Monstro/Dive.anim.meta
  Project C/Assets/Animation/Enemy/Monstro/HighJump.anim
  Project C/Assets/Animation/Enemy/Monstro/Idle.anim
  Project C/Assets/Animation/Enemy/Monstro/JumpReady.anim
  Project C/Assets/Animation/Enemy/Monstro/JumpReady.anim.meta
  Project C/Assets/Animation/Enemy/Monstro/SpitAttack.anim
  Project C/Assets/Animation/Enemy/Monstro/SpitReady.anim
  Project C/Assets/Prefabs/NamGiSan/Boss_bullet.prefab
  Project C/Assets/Resource/Sprite/Enemy/Monstro/Monstro 1.png
  Project C/Assets/Resource/Sprite/Enemy/Monstro/Monstro 1.png.meta
  Project C/Assets/Resource/Sprite/Enemy/Monstro/Monstro.png.meta
  Project C/Assets/Resource/Sprite/Enemy/Monstro/Sprite_Boss_Tears.png
  Project C/Assets/Resource/Sprite/Enemy/Monstro/Sprite_Boss_Tears.png.meta
  Project C/Assets/Resource/Sprite/Enemy/Monstro/Sprite_Enemy_Tears.png
  Project C/Assets/Resource/Sprite/Enemy/Monstro/Sprite_Enemy_Tears.png.meta
  Project C/Assets/Resource/Sprite/Player/Sprite_Player_Isaac.png
  Project C/Assets/Scenes/NamGiSan/NamGiSan.unity
  Project C/Assets/Scripts/LeeJinHo/Manager.meta
  Project C/Assets/Scripts/LeeJinHo/Manager/DataManager.cs.meta
  Project C/Assets/Scripts/NamGiSan/Boss_Bullet.cs
  Project C/Assets/Scripts/NamGiSan/BulletManager.cs
  Project C/Assets/Scripts/NamGiSan/BulletManager.cs.meta
  Project C/Assets/Scripts/NamGiSan/BulletManager_Test.cs
  Project C/Assets/Scripts/NamGiSan/BulletManager_Test.cs.meta
  Project C/Assets/Scripts/NamGiSan/EnemyBullet.cs
  Project C/Assets/Scripts/NamGiSan/EnemyBullet.cs.meta
  Project C/Assets/Scripts/NamGiSan/MonstroController.cs
Labels: enhancement

#175 보물상자 - 드랍 확률 변경
  Project C/Assets/Scripts/LeeJinHo/Manager/ItemManager.cs
  Project C/Assets/Scripts/LeeJinHo/Manager/SpawnManager.cs
  Project C/Assets/Scripts/LeeJinHo/Map/Room.cs
Labels: enhancement

#183 플레이어 스텟구현
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/AttakFly.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Fly.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Gaper.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Mulligan.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Pooter.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnLoigc.meta
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnLoigc/Spawn1.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnLoigc/Spawn1.prefab.meta
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnLoigc/Spawn2.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnLoigc/Spawn2.prefab.meta
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnLoigc/Spawn3.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnLoigc/Spawn4.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnLoigc/Spawn4.prefab.meta
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnLoigc/Spawn5.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnLoigc/Spawn5.prefab.meta
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnLoigc/Spawn6.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnLoigc/Spawn6.prefab.meta
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnLoigc/Spawn7.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnLoigc/Spawn7.prefab.meta
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnLoigc/Spawn8.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnLoigc/Spawn8.prefab.meta
  Project C/Assets/Scenes/LeeHyeukJin/NaviTest.unity
  Project C/Assets/Scripts/LeeHyuekJin/Enemy/HorfController.cs
  Project C/Assets/Scripts/LeeHyuekJin/Enemy/PooterController.cs
  Project C/Assets/Scripts/LeeHyuekJin/PlayerController.cs
  Project C/Assets/Scripts/LeeHyuekJin/PlayerController.cs.meta
  Project C/Assets/Scripts/LeeHyuekJin/PlayerState.meta
  Project C/Assets/Scripts/LeeHyuekJin/PlayerState/PlayerST.cs
  Project C/Assets/Scripts/LeeHyuekJin/PlayerState/PlayerST.cs.meta
  Project C/Assets/Scripts/LeeHyuekJin/PlayerStats.cs
  Project C/Assets/Scripts/LeeHyuekJin/PlayerStats.cs.meta
  Project C/Assets/Scripts/LeeHyuekJin/TestItemStats.cs
  Project C/Assets/Scripts/LeeHyuekJin/TestItemStats.cs.meta
  Project C/Assets/Scripts/LeeJinHo/Managers/RoomManager.cs
  Project C/Assets/Scripts/LeeJinHo/Map/Wall.cs
  Project C/Assets/Scripts/LeeJinHo/New Folder.meta
  Project C/Assets/Scripts/ShinJinHyeok/Player_Attack.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Bullet.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Move.cs
  Project C/Assets/Scripts/ShinJinHyeok/Player_Stat.cs
Labels: enhancement

#184 182-아이작-시스템-상태-구현-수정-2
  Project C/Assets/Resources/Prefab/Issac/Isaac.prefab
  Project C/Assets/Resources/Prefab/Issac/Isaac.prefab.meta
  Project C/Assets/Resources/Prefab/Issac/Issac.prefab
  Project C/Assets/Resources/Prefab/Issac/Issac.prefab.meta
  Project C/Assets/Resources/Prefab/Issac/Issac_getItem.prefab
  Project C/Assets/Resources/Prefab/Issac/Issac_plusHit.prefab.meta
  Project C/Assets/Resources/Sprite/Player/Sprite_Player_Isaac.png.meta
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/Issac/IssacController.cs
  Project C/Assets/Scripts/ShinJinHyeok/IsaacController.cs
  Project C/Assets/Scripts/ShinJinHyeok/IsaacController.cs.meta
Labels: enhancement

#188 프로젝트 에셋 파일 정리
  Project C/Assets/Animation/Character/BulletIdle.anim
  Project C/Assets/Animation/Character/BulletPop.anim
  Project C/Assets/Prefabs/NamGiSan/Enemy_bullet.prefab
  Project C/Assets/Prefabs/NamGiSan/Enemy_bullet.prefab.meta
  Project C/Assets/Prefabs/NamGiSan/Monstro.prefab
  Project C/Assets/Prefabs/NamGiSan/Player_toBoss.prefab
  Project C/Assets/Prefabs/NamGiSan/Player_toBoss.prefab.meta
  Project C/Assets/Resources/Sprite/Enemy/Monstro/Monstro 1.png
  Project C/Assets/Resources/Sprite/Enemy/Monstro/Monstro 1.png.meta
  Project C/Assets/Resources/Sprite/Enemy/Monstro/Sprite_Boss_Tears.png
  Project C/Assets/Resources/Sprite/Enemy/Monstro/Sprite_Boss_Tears.png.meta
  Project C/Assets/Resources/Sprite/Enemy/Monstro/Sprite_Enemy_Tears.png
  Project C/Assets/Resources/Sprite/Enemy/Monstro/Sprite_Enemy_Tears.png.meta
  Project C/Assets/Scenes/NamGiSan/NamGiSan.unity
Labels: enhancement

#195 EnemyCounting 방식 수정 및 Room이 닫히지 않는 버그 수정
  Project C/Assets/Scripts/LeeHyuekJin/Enemy/Enemy.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/RoomManager.cs
Labels: enhancement

#198 황금상자 추가, 박스 애니메이션 수정
  Project C/Assets/Animation/Item/BoxClose.controller
  Project C/Assets/Animation/Item/Close.controller
  Project C/Assets/Animation/Item/Close.controller.meta
  Project C/Assets/Animation/Item/Open.controller
  Project C/Assets/Animation/Item/Open.controller.meta
  Project C/Assets/Prefabs/LeeJinHo/GoldenBox.prefab
  Project C/Assets/Prefabs/LeeJinHo/NormalBox.prefab
  Project C/Assets/Prefabs/LeeJinHo/Square.prefab
  Project C/Assets/Scenes/LeeJInho/LeeJInHo.unity
  Project C/Assets/Scripts/LeeJinHo/Box/Box.cs
  Project C/Assets/Scripts/LeeJinHo/Item/BoxOpen.playable
  Project C/Assets/Scripts/LeeJinHo/Managers/Define.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/ItemManager.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/ItemTest.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/Managers.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/SoundManager.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/SpawnManager.cs
Labels: enhancement

#200 에셋 이름 정리
  Project C/Assets/Resources/Sprite/GoldenBox_Lock.asset
  Project C/Assets/Resources/Sprite/GoldenBox_Lock.asset.meta
  Project C/Assets/Resources/Sprite/GoldenBox_Open.asset
  Project C/Assets/Resources/Sprite/GoldenBox_Open.asset.meta
  Project C/Assets/Resources/Sprite/Item_Active_Dice.asset
  Project C/Assets/Resources/Sprite/Item_Active_Dice.asset.meta
  Project C/Assets/Resources/Sprite/Item_Consume_Bomb.asset
  Project C/Assets/Resources/Sprite/Item_Consume_Bomb.asset.meta
  Project C/Assets/Resources/Sprite/Item_Consume_Key.asset
  Project C/Assets/Resources/Sprite/Item_Consume_Key.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_BadMushroom.asset
  Project C/Assets/Resources/Sprite/Item_Passive_BadMushroom.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_Bat.asset
  Project C/Assets/Resources/Sprite/Item_Passive_Bat.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_Belt.asset
  Project C/Assets/Resources/Sprite/Item_Passive_Belt.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_BlackFace.asset
  Project C/Assets/Resources/Sprite/Item_Passive_BlackFace.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_DogHead.asset
  Project C/Assets/Resources/Sprite/Item_Passive_DogHead.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_Eye.asset
  Project C/Assets/Resources/Sprite/Item_Passive_Eye.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_FeedingBottle.asset
  Project C/Assets/Resources/Sprite/Item_Passive_FeedingBottle.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_GreenSyringe.asset
  Project C/Assets/Resources/Sprite/Item_Passive_GreenSyringe.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_Hanger.asset
  Project C/Assets/Resources/Sprite/Item_Passive_Hanger.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_HeadBand.asset
  Project C/Assets/Resources/Sprite/Item_Passive_HeadBand.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_Magnitude.asset
  Project C/Assets/Resources/Sprite/Item_Passive_Magnitude.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_Mirror.asset
  Project C/Assets/Resources/Sprite/Item_Passive_Mirror.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_Onion.asset
  Project C/Assets/Resources/Sprite/Item_Passive_Onion.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_Panty.asset
  Project C/Assets/Resources/Sprite/Item_Passive_Panty.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_PurpleSyringe.asset
  Project C/Assets/Resources/Sprite/Item_Passive_PurpleSyringe.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_RedHighHeel.asset
  Project C/Assets/Resources/Sprite/Item_Passive_RedHighHeel.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_RedLipstick.asset
  Project C/Assets/Resources/Sprite/Item_Passive_RedLipstick.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_RedSyringe.asset
  Project C/Assets/Resources/Sprite/Item_Passive_RedSyringe.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_SkyMushroom.asset
  Project C/Assets/Resources/Sprite/Item_Passive_SkyMushroom.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_Tear.asset
  Project C/Assets/Resources/Sprite/Item_Passive_Tear.asset.meta
  Project C/Assets/Resources/Sprite/Item_Passive_WoodSpoon.asset
  Project C/Assets/Resources/Sprite/Item_Passive_WoodSpoon.asset.meta
  Project C/Assets/Resources/Sprite/NormalBox_Lock.asset
  Project C/Assets/Resources/Sprite/NormalBox_Lock.asset.meta
  Project C/Assets/Resources/Sprite/NormalBox_Open.asset
  Project C/Assets/Resources/Sprite/NormalBox_Open.asset.meta
  Project C/Assets/Resources/Sprite/Png/Passive.png.meta
  Project C/Assets/Resources/Sprite/Png/Pickups.png.meta
Labels: enhancement

#201 199-플레이어블-캐릭터-공격-기능-구현
  Project C/Assets/Animation/Character/Issac/Tears_Bullet_1.anim
  Project C/Assets/Resources/Issac/Isaac.prefab
  Project C/Assets/Resources/Issac/Tear.prefab
  Project C/Assets/Resources/Issac/Tear.prefab.meta
  Project C/Assets/Resources/Sprite/Player/Sprite_Player_Tears_1.png.meta
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/Issac/IssacController.cs
Labels: enhancement

#204 보스몬스터 이펙트구현
  Project C/Assets/Animation/Character/BulletIdle.anim
  Project C/Assets/Animation/Character/HighJump.anim
  Project C/Assets/Animation/Character/SpitAttack.anim
  Project C/Assets/Prefabs/NamGiSan/Enemy_bullet.prefab
  Project C/Assets/Prefabs/NamGiSan/Monstro.prefab
  Project C/Assets/Resources/Sprite/Enemy/Monstro/Monstro.png.meta
  Project C/Assets/Scenes/NamGiSan/NamGiSan.unity
  Project C/Assets/Scripts/NamGiSan/EnemyBullet.cs
  Project C/Assets/Scripts/NamGiSan/MonstroController.cs
  Project C/Assets/Scripts/NamGiSan/ShockWave.cs
  Project C/Assets/Scripts/NamGiSan/ShockWave.cs.meta
  Project C/Assets/Shader.meta
  Project C/Assets/Shader/ShockWaveScreen.shadergraph
  Project C/Assets/Shader/ShockWaveScreen.shadergraph.meta
  Project C/Assets/Shader/ShockWaveScreenMAT.mat
  Project C/Assets/Shader/ShockWaveScreenMAT.mat.meta
  Project C/Assets/Shader/ShockWaveSprite.shadergraph
  Project C/Assets/Shader/ShockWaveSprite.shadergraph.meta
  Project C/Assets/Shader/ShockWaveSpriteMAT.mat
  Project C/Assets/Shader/ShockWaveSpriteMAT.mat.meta
  Project C/ProjectSettings/TagManager.asset
Labels: enhancement

#205 202-아이작-공격-기능-구현-2
  Project C/Assets/Resources/Issac/Isaac.prefab
  Project C/Assets/Resources/Issac/Tear.prefab
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/Issac/IssacController.cs
Labels: enhancement

#206 enemy 오디오 추가 및 playerstat코드 변경
  Project C/Assets/Material/Materials.meta
  Project C/Assets/Material/Materials/Sprite_Enemy_AttakFly1.mat
  Project C/Assets/Material/Materials/Sprite_Enemy_AttakFly1.mat.meta
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/AttakFly.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Fly.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Gaper.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Horf.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Obstacle/Poop.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Obstacle/RedPoop.prefab
  Project C/Assets/Prefabs/ShinJinHyeok/Sprite_Player_Tear.prefab
  Project C/Assets/Resources/Issac/Tear.prefab
  Project C/Assets/Resources/Sprite/Png/Passive_3.asset
  Project C/Assets/Resources/Sprite/Png/poops.png
  Project C/Assets/Resources/Sprite/Png/poops.png.meta
  Project C/Assets/Scripts/Issac/IssacController.cs
  Project C/Assets/Scripts/LeeHyuekJin/Enemy/EnemyHealth.cs
  Project C/Assets/Scripts/LeeHyuekJin/Enemy/GaperController.cs
  Project C/Assets/Scripts/LeeHyuekJin/Enemy/HorfController.cs
  Project C/Assets/Scripts/LeeHyuekJin/PlayerState/PlayerST.cs
  Project C/Assets/Scripts/LeeHyuekJin/PlayerState/PlayerST.cs.meta
  Project C/Assets/Scripts/LeeJinHo/Managers/ItemTest.cs
Labels: enhancement

#209 207-아이작-공격-애니메이션
  Project C/Assets/Animation/Character/Issac/Tears_Bullet_1.anim
  Project C/Assets/Prefabs/ShinJinHyeok/Player.prefab
  Project C/Assets/Prefabs/ShinJinHyeok/Player.prefab.meta
  Project C/Assets/Prefabs/ShinJinHyeok/Sprite_Player_Tear.prefab
  Project C/Assets/Prefabs/ShinJinHyeok/Sprite_Player_Tear.prefab.meta
  Project C/Assets/Resources/Issac/Isaac.prefab
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/Issac/IssacController.cs
  Project C/Assets/Scripts/LeeHyuekJin/ItemStatsUp.cs.meta
Labels: enhancement

#213 212-아이작-아이템-사용
  Project C/Assets/Resources/Issac/Isaac.prefab
  Project C/Assets/Scripts/Issac/IssacController.cs
Labels: enhancement

#219 215-아이작-충돌-판정
  Project C/Assets/Resources/Issac/Isaac.prefab
  Project C/Assets/Resources/Issac/Tear.prefab
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/Issac/IssacController.cs
  Project C/Assets/Scripts/Issac/PlayerBulletController.cs
  Project C/Assets/Scripts/Issac/PlayerBulletController.cs.meta
Labels: enhancement

#223 폭탄 - 재업로드
  Project C/Assets/Animation/Item/Animation_Bomb.anim
  Project C/Assets/Prefabs/LeeHyuekJin/Bomb.prefab
  Project C/Assets/Scenes/NamGiSan/NamGiSan.unity
  Project C/Assets/Scripts/LeeHyuekJin/BombController.cs
Labels: enhancement

#226 플레이어 - 총알 데미지 구현
  Project C/Assets/Scripts/Issac/IssacController.cs
  Project C/Assets/Scripts/Issac/PlayerBulletController.cs
Labels: enhancement

#228 227-아이템-폭탄-데미지-구현
  Project C/Assets/Resources/Issac/Isaac.prefab
  Project C/Assets/Scenes/LeeHyeukJin/NaviTest.unity
  Project C/Assets/Scripts/LeeHyuekJin/BombController.cs
Labels: enhancement

#230 적-보스몬스터-사망효과
  Project C/Assets/Animation/Character/Animator_Enemy_Monstro.controller
  Project C/Assets/Animation/Character/Dead.anim
  Project C/Assets/Animation/Character/Dead.anim.meta
  Project C/Assets/Animation/Character/Hit.anim
  Project C/Assets/Animation/Character/Hit.anim.meta
  Project C/Assets/Animation/Character/Monstro.meta
  Project C/Assets/Animation/Character/Monstro/Animation_Enemy_Monstro_Blood.anim
  Project C/Assets/Animation/Character/Monstro/Animation_Enemy_Monstro_Blood.anim.meta
  Project C/Assets/Animation/Character/Monstro/Animation_Enemy_Monstro_Blood2.anim
  Project C/Assets/Animation/Character/Monstro/Animation_Enemy_Monstro_Blood2.anim.meta
  Project C/Assets/Animation/Character/Monstro/BloodPOP_0.controller
  Project C/Assets/Animation/Character/Monstro/BloodPOP_0.controller.meta
  Project C/Assets/Animation/Character/Monstro/BloodPOP_ver2_0.controller
  Project C/Assets/Animation/Character/Monstro/BloodPOP_ver2_0.controller.meta
  Project C/Assets/Prefabs/NamGiSan/BloodPOP.prefab
  Project C/Assets/Prefabs/NamGiSan/BloodPOP.prefab.meta
  Project C/Assets/Prefabs/NamGiSan/BloodPOP_ver2.prefab
  Project C/Assets/Prefabs/NamGiSan/BloodPOP_ver2.prefab.meta
  Project C/Assets/Prefabs/NamGiSan/Monstro.prefab
  Project C/Assets/Scenes/NamGiSan/NamGiSan.unity
  Project C/Assets/Scripts/NamGiSan/BossHealth.cs
  Project C/Assets/Scripts/NamGiSan/MonstroController.cs
Labels: enhancement

#231 적 - 사망효과
  Project C/Assets/Animation/Character/Animator_Enemy_Fly.controller
  Project C/Assets/Animation/Character/Enemy_Dead.anim
  Project C/Assets/Animation/Character/Enemy_Dead.anim.meta
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Gaper.prefab
  Project C/Assets/Resources/Sprite/Enemy/Blood/bloodanimation2 1.png
  Project C/Assets/Resources/Sprite/Enemy/Blood/bloodanimation2 1.png.meta
  Project C/Assets/Scripts/LeeHyuekJin/Enemy/EnemyHealth.cs
  Project C/Assets/Scripts/LeeHyuekJin/Enemy/EnemySpawnController.cs
  Project C/Assets/Scripts/LeeHyuekJin/MoveRoom.cs
  Project C/Assets/Scripts/LeeHyuekJin/PlayerStats.cs
Labels: enhancement

#233 224-아이작-아이템-픽업-기능
  Project C/Assets/Animation/Character/Issac/Pickup.anim
  Project C/Assets/Animation/Character/Issac/Pickup.anim.meta
  Project C/Assets/Animation/Character/Issac/Pickup.controller
  Project C/Assets/Animation/Character/Issac/Pickup.controller.meta
  Project C/Assets/Resources/Issac/Isaac.prefab
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/Issac/IssacController.cs
  Project C/Assets/Scripts/Issac/PlayerBulletController.cs
Labels: enhancement

#236 UI매니저 클래스 + LiiJinHo 씬 업데이트
  Project C/Assets/Scenes/LeeJInho/MainMenu.unity
Labels: enhancement

#238 UI매니저 클래스 - 수정
  Project C/Assets/Scripts/LeeJinHo/Data/Define.cs
Labels: enhancement

#241 234-아이작-공격-포인트-설정
  Project C/Assets/Resources/Issac/Isaac.prefab
  Project C/Assets/Resources/Issac/Tear.prefab
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/Issac/IssacController.cs
Labels: enhancement

#243 UI - 플레이어 스텟 및 인벤토리
  Project C/Assets/Scenes/LeeHyeukJin/NaviTest.unity
  Project C/Assets/Scripts/Issac/IssacController.cs
  Project C/Assets/Scripts/LeeHyuekJin/MoveRoom.cs
  Project C/Assets/Scripts/LeeHyuekJin/PlayerStats.cs
  Project C/Assets/Scripts/LeeHyuekJin/TestItemStats.cs
  Project C/Assets/Scripts/LeeHyuekJin/TestItemStats.cs.meta
  Project C/Assets/Scripts/LeeJinHo/Data/Define.cs.meta
  Project C/Assets/Scripts/LeeJinHo/Managers/Define.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/ItemDataTest.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/ItemDataTest.cs.meta
  Project C/Assets/Scripts/LeeJinHo/Managers/ItemTest.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/ItemTest.cs.meta
  Project C/Assets/Scripts/LeeJinHo/Managers/Managers.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/RoomManager.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/UIManager.cs
  Project C/Assets/Scripts/LeeJinHo/Test/Test_Player_Move.cs
  Project C/Assets/Scripts/LeeJinHo/Test/Test_Player_Move.cs.meta
Labels: enhancement

#244 UI 설정창 UI 구현
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/AttakFly.prefab
  Project C/Assets/Resources/Sprite/Enemy/Monstro/BGTEST.png
  Project C/Assets/Resources/Sprite/Enemy/Monstro/BGTEST.png.meta
  Project C/Assets/Resources/Sprite/Menu/optionsmenudark.png
  Project C/Assets/Resources/Sprite/Menu/optionsmenudark.png.meta
  Project C/Assets/Resources/Sprite/Menu/whitecounter.png
  Project C/Assets/Resources/Sprite/Menu/whitecounter.png.meta
  Project C/Assets/Scenes/NamGiSan/MenuSystem.unity
  Project C/Assets/Scenes/NamGiSan/MenuSystem.unity.meta
  Project C/Assets/Scenes/NamGiSan/NamGiSan.unity
  Project C/Assets/Scripts/NamGiSan/BossHealth.cs
  Project C/Assets/Scripts/NamGiSan/MonstroController.cs
  Project C/Assets/Scripts/NamGiSan/PauseMenu.cs
Labels: enhancement

#246 하트 구현
  Project C/Assets/Prefabs/LeeHyuekJin/Heart.meta
  Project C/Assets/Prefabs/LeeHyuekJin/Heart/HalfHeart.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Heart/HalfHeart.prefab.meta
  Project C/Assets/Prefabs/LeeHyuekJin/Heart/Heart.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Heart/Heart.prefab.meta
  Project C/Assets/Scripts/LeeHyuekJin/Enemy/Enemy.cs
  Project C/Assets/Scripts/LeeHyuekJin/Heart.cs
  Project C/Assets/Scripts/LeeHyuekJin/Heart.cs.meta
  Project C/Assets/Scripts/LeeHyuekJin/PlayerStats.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/UIManager.cs
Labels: enhancement

#249 248-이동-스프라이트-변경
  Project C/Assets/Resources/Issac/Isaac.prefab
  Project C/Assets/Scripts/Issac/IssacController.cs
Labels: enhancement

#251 250-아이작-기능-수정
  Project C/Assets/Resources/Issac/Isaac.prefab
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/Issac/IssacController.cs
Labels: enhancement

#253 씬 결합
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/AttakFly.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Fly.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Gaper.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Horf.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Mulligan.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Pooter.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Obstacle/Materials/block3.mat
  Project C/Assets/Prefabs/LeeHyuekJin/Obstacle/Materials/block3.mat.meta
  Project C/Assets/Prefabs/LeeHyuekJin/Spawn.meta
  Project C/Assets/Prefabs/LeeHyuekJin/Spawn/Spawn1.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Spawn/Spawn1.prefab.meta
  Project C/Assets/Prefabs/LeeHyuekJin/Spawn/Spawn2.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Spawn/Spawn2.prefab.meta
  Project C/Assets/Prefabs/LeeHyuekJin/Spawn/Spawn3.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Spawn/Spawn3.prefab.meta
  Project C/Assets/Prefabs/LeeHyuekJin/Spawn/Spawn4.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Spawn/Spawn4.prefab.meta
  Project C/Assets/Prefabs/LeeHyuekJin/Spawn/Spawn5.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Spawn/Spawn5.prefab.meta
  Project C/Assets/Prefabs/LeeHyuekJin/SpawnObject/Spawn3.prefab
  Project C/Assets/Resources/Sprite/Enemy/AttakFly/Sprite_Enemy_AttakFly1.png.meta
  Project C/Assets/Resources/Sprite/Enemy/Fly/Sprite_Enemy_AttakFly1.png.meta
  Project C/Assets/Resources/Sprite/Enemy/Fly/Sprite_Enemy_AttakFly2.png.meta
  Project C/Assets/Resources/Sprite/Enemy/Horf/PC Computer - The Binding of Isaac Rebirth - Horf.png.meta
  Project C/Assets/Resources/Sprite/Enemy/Mulligan/ebodyidle.png.meta
  Project C/Assets/Resources/Sprite/Enemy/Mulligan/mulliganhead.png.meta
  Project C/Assets/Resources/Sprite/Png/Passive.png.meta
  Project C/Assets/Resources/Sprite/Png/pickup_hearts.png.meta
  Project C/Assets/Scenes/LeeHyeukJin/NaviTest.unity
  Project C/Assets/Scenes/LeeHyeukJin/Stage1.unity
  Project C/Assets/Scenes/LeeHyeukJin/Stage1.unity.meta
  Project C/Assets/Scripts/Issac/IssacController.cs
  Project C/Assets/Scripts/LeeHyuekJin/BombController.cs
  Project C/Assets/Scripts/LeeHyuekJin/Enemy/Enemy.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/Item.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/RoomManager.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/UIManager.cs
  Project C/Assets/Scripts/NamGiSan/PauseMenu.cs
Labels: enhancement

#276 박스 - 버그 수정
  Project C/Assets/Prefabs/LeeJinHo/GoldenBox.prefab
  Project C/Assets/Prefabs/LeeJinHo/NormalBox.prefab
  Project C/Assets/Scripts/LeeJinHo/Item/Item.cs
Labels: bug

#277 258-아이작-눈물-중력
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/Issac/IssacController.cs
  Project C/Assets/Scripts/NamGiSan/EnemyBullet.cs
Labels: enhancement

#278 사운드 UI
  Project C/Assets/Scenes/LeeHyeukJin/Stage1.unity
  Project C/Assets/Scripts/LeeHyuekJin/VolumeController.cs
  Project C/Assets/Scripts/LeeHyuekJin/VolumeController.cs.meta
  Project C/Assets/Scripts/LeeJinHo/Managers/SoundManager.cs
Labels: enhancement

#281 아이템 움직임 추가
  Project C/Assets/Scripts/LeeJinHo/Item/Item.cs
Labels: enhancement

#282 적 투사체 수정
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Gaper.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Horf.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Mulligan.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Pooter.prefab
  Project C/Assets/Scenes/NamGiSan/NamGiSan.unity
  Project C/Assets/Scripts/LeeHyuekJin/Enemy/HorfController.cs
  Project C/Assets/Scripts/LeeHyuekJin/Enemy/PooterController.cs
Labels: bug

#284 보스 사망버그 수정
  Project C/Assets/Animation/Character/Animator_Enemy_Monstro.controller
  Project C/Assets/Animation/Character/Dead.anim
  Project C/Assets/Animation/Character/Hit.anim
  Project C/Assets/Prefabs/LeeJinHo/RandomMap 1.prefab.meta
  Project C/Assets/Prefabs/NamGiSan/Monstro.prefab
  Project C/Assets/Scenes/NamGiSan/NamGiSan.unity
  Project C/Assets/Scripts/NamGiSan/BossHealth.cs
  Project C/Assets/Scripts/NamGiSan/MonstroController.cs
Labels: bug

#285 보스 - 보상
  Project C/Assets/Prefabs/NamGiSan/Monstro.prefab
  Project C/Assets/Scripts/LeeHyuekJin/BossRoom.cs
  Project C/Assets/Scripts/LeeHyuekJin/BossSpawner.cs
  Project C/Assets/Scripts/LeeHyuekJin/BossSpawner.cs.meta
  Project C/Assets/Scripts/LeeHyuekJin/Enemy/Enemy.cs
Labels: enhancement

#287 버그 수정
  Project C/Assets/Plugins/System.Linq.Async.dll
  Project C/Assets/Plugins/System.Linq.Async.dll.meta
  Project C/Assets/Prefabs/LeeHyuekJin/Bomb.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Heart/HalfHeart.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Heart/Heart.prefab
  Project C/Assets/Scripts/LeeJinHo/Item/Item.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/UIManager.cs
Labels: bug

#290 269-아이작-사운드-추가
  Project C/Assets/Animation/Character/Issac/DownAttack.anim
  Project C/Assets/Animation/Character/Issac/IdleAttack.anim
  Project C/Assets/Animation/Character/Issac/LeftAttack.anim
  Project C/Assets/Animation/Character/Issac/RightAttack.anim
  Project C/Assets/Animation/Character/Issac/UpAttack.anim
  Project C/Assets/Resources/AudioClip/TearImpacts2.mp3
  Project C/Assets/Resources/AudioClip/TearImpacts2.mp3.meta
  Project C/Assets/Resources/Issac/Isaac.prefab
  Project C/Assets/Resources/Issac/Tear.prefab
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/Issac/IssacController.cs
  Project C/Assets/Scripts/Issac/PlayerBulletController.cs
Labels: enhancement

#293 적 투사체 풀링 시스템 이용
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Horf.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Mulligan.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Pooter.prefab
  Project C/Assets/Prefabs/NamGiSan/EnemyBulletPool.prefab
  Project C/Assets/Prefabs/NamGiSan/EnemyBulletPool.prefab.meta
  Project C/Assets/Prefabs/NamGiSan/Enemybullet.prefab
  Project C/Assets/Prefabs/NamGiSan/Enemybullet.prefab.meta
  Project C/Assets/Scenes/NamGiSan/NamGiSan.unity
  Project C/Assets/Scripts/LeeHyuekJin/Enemy/HorfController.cs
  Project C/Assets/Scripts/LeeHyuekJin/Enemy/MulliganController.cs
  Project C/Assets/Scripts/LeeHyuekJin/Enemy/PooterController.cs
  Project C/Assets/Scripts/NamGiSan/BulletManager.cs
  Project C/Assets/Scripts/NamGiSan/EnemyBullet.cs
  Project C/Assets/Scripts/NamGiSan/EnemyBullet.cs.meta
  Project C/Assets/Scripts/NamGiSan/EnemyBulletPoolManager.cs
  Project C/Assets/Scripts/NamGiSan/EnemyBulletPoolManager.cs.meta
  Project C/Assets/Scripts/NamGiSan/MonstroController.cs
Labels: enhancement

#294 사운드 컨트롤
  Project C/Assets/Prefabs/LeeHyuekJin/RandomMapReal2.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/RandomMapReal2.prefab.meta
  Project C/Assets/Resources/Issac/Isaac.prefab
  Project C/Assets/Scenes/LeeHyeukJin/Stage1.unity
  Project C/Assets/Scripts/LeeHyuekJin/BossRoom.cs
  Project C/Assets/Scripts/LeeHyuekJin/VolumeController.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/RoomManager.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/SoundManager.cs
Labels: enhancement

#295 주사위 기능
  Project C/Assets/Scripts/LeeJinHo/Item/ActiveItem/Item_Dice.cs
  Project C/Assets/Scripts/LeeJinHo/Item/Item.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/ItemManager.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/ResourceManager.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/RoomManager.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/UIManager.cs
Labels: enhancement

#298 UI-보스컷신
  Project C/Assets/Animation/UI/BossCutScene.anim
  Project C/Assets/Animation/UI/BossCutScene.anim.meta
  Project C/Assets/Animation/UI/BossCutScene.controller
  Project C/Assets/Animation/UI/BossCutScene.controller.meta
  Project C/Assets/Prefabs/NamGiSan/Monstro.prefab
  Project C/Assets/Scenes/NamGiSan/BossCutScene.meta
  Project C/Assets/Scenes/NamGiSan/BossCutScene/BossCutScene.prefab
  Project C/Assets/Scenes/NamGiSan/BossCutScene/BossCutScene.prefab.meta
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss.meta
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/CutScene.cs
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/CutScene.cs.meta
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/bgblack.png
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/bgblack.png.meta
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/bossname_20.0_monstro.png
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/bossname_20.0_monstro.png.meta
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/bossname_36.0_gurdy.png
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/bossname_36.0_gurdy.png.meta
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/bossname_79.0_gemini.png
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/bossname_79.0_gemini.png.meta
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/bossspot_01_basement.png
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/bossspot_01_basement.png.meta
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/playername_01_isaac.png
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/playername_01_isaac.png.meta
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/playerspot_01_basement.png
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/playerspot_01_basement.png.meta
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/portrait_102.0_isaac.png
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/portrait_102.0_isaac.png.meta
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/portrait_20.0_monstro.png
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/portrait_20.0_monstro.png.meta
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/portrait_36.0_gurdy.png
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/portrait_36.0_gurdy.png.meta
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/vs.png
  Project C/Assets/Scenes/NamGiSan/BossCutScene/boss/vs.png.meta
  Project C/Assets/Scenes/NamGiSan/BossEnter.unity
  Project C/Assets/Scenes/NamGiSan/BossEnter.unity.meta
  Project C/Assets/Scenes/NamGiSan/NamGiSan.unity
Labels: enhancement

#300 보스 컷씬
  Project C/Assets/Scenes/LeeHyeukJin/Stage1.unity
  Project C/Assets/Scripts/LeeHyuekJin/BossRoom.cs
  Project C/Assets/Scripts/NamGiSan/BossHealth.cs
Labels: enhancement

#302 빌드 버그 수정
  Project C/Assets/Scripts/LeeJinHo/Data/Define.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/DataManager.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/ResourceManager.cs
Labels: bug

#304 303-아이작-풀링-구현-및-충돌-수정
  Project C/Assets/Animation/Character/EnemyBullet.controller
  Project C/Assets/Animation/Character/Issac/BulletIdle.anim
  Project C/Assets/Animation/Character/Issac/BulletIdle.anim.meta
  Project C/Assets/Animation/Character/Issac/Pickup.controller
  Project C/Assets/Animation/Character/Issac/Tears.controller
  Project C/Assets/Resources/Issac/Isaac.prefab
  Project C/Assets/Resources/Issac/Tear.prefab
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/Issac/IssacController.cs
  Project C/Assets/Scripts/Issac/PlayerBulletController.cs
  Project C/Assets/Scripts/Issac/PlayerBulletPool.cs
  Project C/Assets/Scripts/Issac/PlayerBulletPool.cs.meta
Labels: enhancement

#306 275-아이작-픽업-애니메이션
  Project C/Assets/Animation/Character/Issac/Isaac.controller
  Project C/Assets/Animation/Character/Issac/Isaac.controller.meta
  Project C/Assets/Animation/Character/Issac/Pickup.anim
  Project C/Assets/Resources/Issac/Isaac.prefab
  Project C/Assets/Resources/Issac/Tear.prefab
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/Issac/IssacController.cs
Labels: enhancement

#308 보스소환 이펙트
  Project C/Assets/Animation/Character/BombEffect_0.controller
  Project C/Assets/Animation/Character/BombEffect_0.controller.meta
  Project C/Assets/Animation/Character/BossSpawnEffect.anim
  Project C/Assets/Animation/Character/BossSpawnEffect.anim.meta
  Project C/Assets/Prefabs/NamGiSan/BossSpawnEffect.prefab
  Project C/Assets/Prefabs/NamGiSan/BossSpawnEffect.prefab.meta
  Project C/Assets/Resources/Sprite/Png/BombEffect.png.meta
  Project C/Assets/Scenes/NamGiSan/NamGiSan.unity
  Project C/Assets/Scenes/NamGiSan/Pause.unity
Labels: enhancement

#312 311-아이작-픽업-모션-제한
  Project C/Assets/Resources/Data/Item.csv
  Project C/Assets/Resources/Issac/IsaacPoolManager.prefab
  Project C/Assets/Resources/Issac/IsaacPoolManager.prefab.meta
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/Issac/IssacController.cs
  Project C/Assets/Scripts/Issac/PlayerBulletController.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/DataManager.cs
Labels: enhancement

#317 애니메이션 및 소리 수정
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/AttakFly.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Fly.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Horf.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Mulligan.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Pooter.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Spawn/Spawn2.prefab
  Project C/Assets/Prefabs/NamGiSan/BloodPOP(17).prefab
  Project C/Assets/Prefabs/NamGiSan/Monstro.prefab
  Project C/Assets/Resources/Issac/Isaac.prefab
  Project C/Assets/Resources/Sprite/Png/UI_Tear.png
  Project C/Assets/Resources/Sprite/Png/UI_Tear.png.meta
  Project C/Assets/Scenes/LeeHyeukJin/Stage1.unity
  Project C/Assets/Scripts/LeeHyuekJin/Heart.cs
  Project C/Assets/Scripts/LeeJinHo/Item/ActiveItem/Item_Dice.cs
  Project C/Assets/Scripts/LeeJinHo/Item/Item.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/SoundManager.cs
  Project C/Assets/Scripts/NamGiSan/BossHealth.cs
  Project C/Assets/Scripts/NamGiSan/MonstroController.cs
Labels: enhancement

#321 비율 수정 애니메이션
  Project C/Assets/Animation/Character/Monstro/Animation_Enemy_Monstro_Blood4.anim
  Project C/Assets/Prefabs/NamGiSan/Monstro.prefab
  Project C/Assets/Resources/Sprite/Enemy/Monstro/effect_077_largebloodexplosion 1.png
  Project C/Assets/Resources/Sprite/Enemy/Monstro/effect_077_largebloodexplosion 1.png.meta
Labels: enhancement

#323 리턴 씬 구현
  Project C/Assets/Scenes/LeeHyeukJin/RetrunScene.unity
  Project C/Assets/Scenes/LeeHyeukJin/RetrunScene.unity.meta
  Project C/Assets/Scripts/LeeJinHo/Menu/MenuButton.cs
  Project C/Assets/Scripts/NamGiSan/PauseMenu.cs
Labels: enhancement

#325 324-아이작-스크립트-수정
  Project C/Assets/Scripts/Issac/IssacController.cs
  Project C/Assets/Scripts/Issac/PlayerBulletController.cs
Labels: enhancement

#327 통로생성
  Project C/Assets/Animation/UI/BasementDoor.anim
  Project C/Assets/Animation/UI/BasementDoor.anim.meta
  Project C/Assets/Animation/UI/BasementDoor.controller
  Project C/Assets/Animation/UI/BasementDoor.controller.meta
  Project C/Assets/Resources/Prefab/0_NextLevelDoor.prefab
  Project C/Assets/Resources/Prefab/0_NextLevelDoor.prefab.meta
  Project C/Assets/Resources/Sprite/Png/door_nextStage.png
  Project C/Assets/Resources/Sprite/Png/door_nextStage.png.meta
  Project C/Assets/Scenes/NamGiSan/NamGiSan.unity
  Project C/Assets/Scripts/Issac/MouseController.cs.meta
Labels: enhancement

#331 버그 수정
  Project C/Assets/Prefabs/LeeHyuekJin/Bomb.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Gaper.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Enemy/Mulligan.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Heart/HalfHeart.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Spawn/Spawn4.prefab
  Project C/Assets/Prefabs/LeeHyuekJin/Spawn/Spawn5.prefab
  Project C/Assets/Scenes/LeeHyeukJin/Stage1.unity
  Project C/Assets/Scripts/NamGiSan/PauseMenu.cs
Labels: bug

#333 332-아이작-총알-수정
  Project C/Assets/Scenes/ShinJinHyeok/ShinJinHyeok.unity
  Project C/Assets/Scripts/Issac/IssacController.cs
  Project C/Assets/Scripts/Issac/PlayerBulletPool.cs
  Project C/Assets/Scripts/NamGiSan/EnemyBulletPoolManager.cs
Labels: enhancement

#337 하트 버그 해결
  Project C/Assets/Prefabs/LeeHyuekJin/Heart/HalfHeart.prefab
  Project C/Assets/Scripts/LeeHyuekJin/PlayerStats.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/UIManager.cs
Labels: bug

#339 엔딩씬
  Project C/Assets/Resources/AudioClip/Vidio_Stage1_Clear.mp4
  Project C/Assets/Resources/AudioClip/Vidio_Stage1_Clear.mp4.meta
  Project C/Assets/Resources/Prefab/NextLevelDoor.prefab
  Project C/Assets/Resources/Prefab/NextLevelDoor.prefab.meta
  Project C/Assets/Scripts/LeeJinHo/Managers/SoundManager.cs
  Project C/Assets/Scripts/LeeJinHo/Managers/SpawnManager.cs
  Project C/Assets/Scripts/LeeJinHo/New Folder/NextstageTest.cs
  Project C/Assets/Scripts/LeeJinHo/New Folder/NextstageTest.cs.meta
  Project C/Assets/Scripts/NamGiSan/BossHealth.cs
Labels: enhancement

#341 엔딩씬 수정
  Project C/Assets/Prefabs/LeeJinHo/RealNextLevelDoor.prefab
  Project C/Assets/Prefabs/LeeJinHo/RealNextLevelDoor.prefab.meta
  Project C/Assets/Scenes/LeeJInho/End.unity
  Project C/Assets/Scenes/LeeJInho/End.unity.meta
  Project C/Assets/Scripts/LeeJinHo/New Folder/NextstageTest.cs
  Project C/Assets/Scripts/LeeJinHo/New Folder/Video.cs
  Project C/Assets/Scripts/LeeJinHo/New Folder/Video.cs.meta
  Project C/Assets/Scripts/NamGiSan/BossHealth.cs
Labels: enhancement
